### ISSUE TITLE
Unable to proceed following the readme instructions for the Developer quickstart

### ISSUE THREAD

**Issue by sswaroopgupta** [ThoughtWorksStudios/bobcat#1]
**Step to replicate**
* Start docker
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/


docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

* Cloning the given url
inblr-username:gauge username$ git clone https://github.com/ThoughtWorksStudios/datagen.git
Cloning into 'datagen'...
remote: Counting objects: 1351, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 1351 (delta 32), reused 88 (delta 23), pack-reused 1244
Receiving objects: 100% (1351/1351), 300.42 KiB | 178.00 KiB/s, done.
Resolving deltas: 100% (799/799), done.

* make docker
inblr-username:gauge username$ make docker
make: *** No rule to make target `docker'.  Stop.

* tried after cd datagen. still couldn't get it to work
inblr-username:gauge username$ cd datagen/
inblr-username:datagen username$ make docker
docker pull kyleolivo/datagen
make: docker: No such file or directory
make: *** [docker] Error 1

Please help.

**Comment by kyleolivo** [comment]
Hi Soumya,

Do you have Docker for Mac installed?
https://store.docker.com/editions/community/docker-ce-desktop-mac

I just tried from a new machine and all is well. Terminal dump is below:

`**kyleolivo@Kyles-MacBook-Pro ~>** cd ~/Developer/
**kyleolivo@Kyles-MacBook-Pro ~/Developer>** git clone https://github.com/ThoughtWorksStudios/datagen.git
Cloning into 'datagen'...
remote: Counting objects: 1351, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 1351 (delta 32), reused 88 (delta 23), pack-reused 1244
Receiving objects: 100% (1351/1351), 300.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (799/799), done.
**kyleolivo@Kyles-MacBook-Pro ~/Developer>** cd datagen/
**kyleolivo@Kyles-MacBook-Pro ~/D/datagen (master)>** make docker
make: go: Command not found
docker pull kyleolivo/datagen
Using default tag: latest
latest: Pulling from kyleolivo/datagen
ad74af05f5a2: Pull complete 
2b032b8bbe8b: Pull complete 
a9a5b35f6ead: Pull complete 
25d9840c55bc: Pull complete 
d792ec7d64a3: Pull complete 
be556a93c22e: Pull complete 
3a5fce283a1e: Pull complete 
5490991a677f: Pull complete 
e5cba9348df6: Pull complete 
09daff76651c: Pull complete 
eacfe1d05684: Pull complete 
a663a48ee682: Pull complete 
Digest: sha256:a0dd5b538432736fdd353daaca9e0be48822e6a43122f3d0be0c06d09e435754
Status: Downloaded newer image for kyleolivo/datagen:latest
docker run -h development -it --rm -v `pwd`:/go/src/github.com/ThoughtWorksStudios/datagen kyleolivo/datagen
go get github.com/mna/pigeon
go get -d
/go/bin/pigeon -o dsl/dsl.go dsl/dsl.peg
go build
go test ./interpreter/ ./generator/ ./dsl ./dictionary ./
ok  	github.com/ThoughtWorksStudios/datagen/interpreter	0.015s
ok  	github.com/ThoughtWorksStudios/datagen/generator	0.048s
ok  	github.com/ThoughtWorksStudios/datagen/dsl	0.052s
ok  	github.com/ThoughtWorksStudios/datagen/dictionary	11.444s
?   	github.com/ThoughtWorksStudios/datagen	[no test files]
./datagen example.lang
**root@development:/go/src/github.com/ThoughtWorksStudios/datagen#**`

That last line is a terminal prompt from inside the docker container.

(I do see a little bug related to the GOPATH in my output above, but it shouldn't impact you if you are running from a docker container).

Let me know if the above output helps.

- Kyle

**Comment by kyleolivo** [comment]
Looking at this a little more, there is a line in the output you provided that says:
"make: docker: No such file or directory"

That definitely indicates that Docker for Mac is not installed correctly. You can use the "Get Docker" link here to install that:

https://store.docker.com/editions/community/docker-ce-desktop-mac

Kyle

**Comment by sguptatw** [comment]
Thanks Kyle. Yes, there was some docker installation issue. Working on getting it fixed.
